### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gnaeus** [gnaeus/MultiIndexCollection#1]
### Features
- [x] Indexing for `null` property values
- [x] Implement `ComparsionIndex`
- [x] Other LINQ Methods
- [x] Integration with `INotifyPropertyChanged`
- [x] Integration with `INotifyCollectionChanged`

### Docs
- [ ] README
- [x] XML Comments
- [ ] XML Comments for LINQ methods
- [ ] Benchmark Results
- [ ] GitHub Tags

### Tests
- [x] Indexing
- [x] Updating
- [x] Filtering
- [x] Filtering by complex expressions
- [x] Other LINQ Methods
- [ ] `NotSupported` and `InvalidOperation`

### Benchmarks
- [x] Indexing
- [ ] Updating
- [x] Filtering
- [x] Other LINQ Methods

### Infrastructure
- [ ] Appveyor CI
- [ ] NuGet package
- [ ] Logo
- [ ] Badges

### Other
- [x] Optimize `() => obj.Property == (int?)42` expression argument extraction
